services:
  golembrar-api:
    container_name: goLembrar-api
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    image: golembrar/api:1.0
    env_file: ".env.dev"
    volumes:
      - .:/app
    depends_on:
      - golembrar-db
      - golembrar-cache
      - golembrar-rabbitmq
    restart: unless-stopped

  golembrar-db:
    image: docker.io/library/bitnami/postgresql:17.0.0
    container_name: golembrar-db
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=golembrar
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./.docker/golembrar-db/data:/var/lib/golembrar-db/:delegated
    healthcheck:
      test: [ 'CMD-SHELL', "psql -h localhost -U test -d golembrar -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  golembrar-rabbitmq:
    image: docker.io/library/rabbitmq:4.0-alpine
    container_name: golembrar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/golembrar-rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    depends_on:
      - golembrar-db

  golembrar-cache:
    image: docker.io/library/bitnami/keydb:6.3
    container_name: golembrar-cache
    ports:
      - 6379:6379
    environment:
      - KEYDB_REPLICATION_MODE=master
      - KEYDB_PASSWORD=pass123
    volumes:
      - ./.docker/golembrar-cache/data:/var/lib/keydb-persistence:/bitnami

volumes:
  golembrar-db:
  golembrar-rabbitmq:
  golembrar-cache:
